import { StyleSheet } from "react-native";
import colors from "@/constants/colors";
import sizes from "@/constants/sizes";

const profileColors = {
  page: colors.page,
  brand: colors.brand,
  ink: colors.ink,
  inkMuted: colors.inkMuted,
  inkSoft: colors.inkSoft,
  inkStrong: colors.inkStrong,
  borderStrong: colors.borderStrong,
  borderMuted: colors.borderMuted,
  surfaceMuted: colors.surfaceMuted,
  surfaceSoft: colors.surfaceSoft,
  surfaceAccent: colors.surfaceAccent,
  surfaceSubtle: colors.surfaceSubtle,
  surfaceIcon: colors.surfaceIcon,
  surfaceOverlay: colors.surfaceOverlay,
  overlay: colors.overlay,
  overlayLight: colors.overlayLight,
};

const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: profileColors.page,
  },
  topSection: {
    flex: 1,
    alignItems: "center",
  },
  coverBlock: {
    width: "100%",
    height: 190,
    backgroundColor: profileColors.surfaceSoft,
  },
  avatarBox: {
    marginTop: -120,
    width: 250,
    height: 250,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarWrap: {
    width: "100%",
    height: "100%",
    borderWidth: 4,
    borderColor: colors.white,
    borderRadius: 125,
    overflow: "hidden",
    backgroundColor: profileColors.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraButton: {
    position: "absolute",
    right: -2,
    bottom: 24,
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: profileColors.surfaceMuted,
    borderWidth: 2,
    borderColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
  },
  nameText: {
    marginTop: sizes.xl,
    fontSize: 24,
    fontWeight: "800",
    color: colors.text,
  },
  scrollContent: {
    paddingBottom: sizes.xl,
    gap: 8,
  },
  hero: {
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: profileColors.borderStrong,
  },
  cover: {
    width: "100%",
    height: 178,
    backgroundColor: profileColors.surfaceSoft,
  },
  coverImage: {
    width: "100%",
    height: "100%",
  },
  coverFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.surfaceSoft,
  },
  heroBody: {
    paddingHorizontal: sizes.lg,
    paddingBottom: sizes.lg,
  },
  avatarOverlap: {
    width: 126,
    height: 126,
    borderRadius: 63,
    marginTop: -62,
    borderWidth: 4,
    borderColor: colors.white,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImage: {
    backgroundColor: profileColors.surfaceMuted,
  },
  avatarFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.surfaceAccent,
  },
  avatarFallbackText: {
    color: colors.primary,
    fontWeight: "900",
  },
  fbHero: {
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: profileColors.borderStrong,
  },
  fbCover: {
    height: 178,
    marginHorizontal: sizes.md,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    overflow: "hidden",
    backgroundColor: profileColors.borderMuted,
  },
  fbCoverFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.borderMuted,
  },
  fbCoverCamera: {
    position: "absolute",
    right: 12,
    bottom: 12,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  fbHeroInfo: {
    paddingHorizontal: sizes.md,
    paddingBottom: sizes.md,
  },
  fbAvatarRow: {
    height: 70,
    alignItems: "center",
  },
  fbAvatarBorder: {
    borderWidth: 4,
    borderColor: colors.white,
    backgroundColor: colors.white,
    marginTop: -66,
  },
  fbAvatarCamera: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.white,
  },
  fbName: {
    marginTop: 2,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
    color: profileColors.ink,
    textAlign: "center",
  },
  fbUsername: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: profileColors.ink,
  },
  fbBio: {
    marginTop: sizes.xs,
    fontSize: 15,
    lineHeight: 20,
    color: profileColors.ink,
    textAlign: "center",
  },
  fbActionRow: {
    marginTop: sizes.md,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  fbOwnActionRow: {
    justifyContent: "flex-end",
  },
  fbProfileDetails: {
    marginTop: sizes.sm,
    paddingTop: sizes.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: profileColors.borderMuted,
    gap: 8,
  },
  fbProfileDetailRow: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  fbProfileDetailText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: profileColors.inkSoft,
  },
  fbProfileDetailStrong: {
    fontWeight: "900",
    color: profileColors.ink,
  },
  fbButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 7,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    backgroundColor: profileColors.brand,
  },
  fbButtonCompact: {
    flex: 0,
  },
  fbButtonSecondary: {
    backgroundColor: profileColors.surfaceMuted,
  },
  fbIconButton: {
    flex: 0,
    width: 44,
    minHeight: 38,
    paddingHorizontal: 0,
    backgroundColor: profileColors.surfaceMuted,
  },
  fbButtonIconSlot: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  fbIconButtonSlot: {
    width: 24,
    height: 24,
  },
  fbButtonText: {
    color: colors.white,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    flexShrink: 1,
  },
  fbButtonTextDark: {
    color: profileColors.ink,
  },
  fbTabs: {
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: profileColors.borderStrong,
  },
  fbTabsContent: {
    paddingHorizontal: sizes.md,
    alignItems: "center",
    gap: 2,
  },
  fbTab: {
    minHeight: 52,
    paddingHorizontal: sizes.md,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 3,
    borderBottomColor: "transparent",
  },
  fbTabActive: {
    borderBottomColor: profileColors.brand,
  },
  fbTabText: {
    fontSize: 15,
    fontWeight: "800",
    color: profileColors.inkMuted,
  },
  fbTabTextActive: {
    color: profileColors.brand,
  },
  fbTabMore: {
    width: 48,
    height: 38,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.surfaceMuted,
    marginLeft: sizes.xs,
  },
  fbBody: {
    gap: 8,
  },
  fbCard: {
    marginHorizontal: sizes.md,
    borderRadius: 8,
    backgroundColor: colors.white,
    padding: sizes.md,
    gap: sizes.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileColors.surfaceMuted,
  },
  fbCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: sizes.md,
  },
  fbCardTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: profileColors.ink,
  },
  fbCardSubtitle: {
    marginTop: 2,
    fontSize: 14,
    color: profileColors.inkMuted,
  },
  fbBlueText: {
    color: profileColors.brand,
    fontSize: 15,
    fontWeight: "700",
  },
  fbIntroBio: {
    paddingBottom: sizes.sm,
    fontSize: 15,
    lineHeight: 20,
    color: profileColors.ink,
    textAlign: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: profileColors.borderStrong,
  },
  fbIntroRow: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.sm,
  },
  fbIntroText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    color: profileColors.ink,
  },
  fbIntroLink: {
    color: profileColors.brand,
    fontWeight: "700",
  },
  fbWideGrayButton: {
    minHeight: 40,
    borderRadius: 7,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  fbWideGrayButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: profileColors.ink,
  },
  fbAboutPills: {
    gap: sizes.sm,
  },
  fbAboutPill: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: sizes.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.page,
  },
  fbAboutPillActive: {
    backgroundColor: colors.primaryLight,
  },
  fbAboutPillText: {
    fontSize: 14,
    fontWeight: "800",
    color: profileColors.inkMuted,
  },
  fbAboutPillTextActive: {
    color: profileColors.brand,
  },
  fbSubheading: {
    fontSize: 17,
    fontWeight: "900",
    color: profileColors.ink,
  },
  fbBioLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.sm,
  },
  fbComposerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.sm,
  },
  fbComposerInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: sizes.md,
    alignItems: "flex-start",
    justifyContent: "center",
    backgroundColor: profileColors.page,
  },
  fbComposerText: {
    fontSize: 15,
    color: profileColors.inkMuted,
  },
  fbComposerActions: {
    paddingTop: sizes.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: profileColors.borderStrong,
    flexDirection: "row",
  },
  fbComposerAction: {
    flex: 1,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  fbComposerActionText: {
    fontSize: 13,
    fontWeight: "800",
    color: profileColors.inkMuted,
  },
  fbSmallGrayButton: {
    minHeight: 34,
    borderRadius: 7,
    paddingHorizontal: sizes.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: profileColors.surfaceMuted,
  },
  fbSmallGrayButtonText: {
    color: profileColors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  moreButton: {
    position: "absolute",
    top: sizes.md,
    right: sizes.lg,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  profileName: {
    marginTop: sizes.sm,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900",
    color: profileColors.ink,
  },
  description: {
    marginTop: sizes.xs,
    fontSize: 15,
    lineHeight: 21,
    color: colors.text,
  },
  metaList: {
    marginTop: sizes.md,
    gap: sizes.xs,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.xs,
  },
  metaText: {
    flex: 1,
    fontSize: 14,
    color: colors.subtext,
  },
  linkText: {
    flex: 1,
    fontSize: 14,
    color: colors.primary,
    fontWeight: "700",
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: sizes.sm,
    marginTop: sizes.lg,
  },
  pillButton: {
    minHeight: 42,
    borderRadius: 999,
    paddingHorizontal: sizes.md,
    paddingVertical: sizes.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: sizes.xs,
    backgroundColor: profileColors.brand,
  },
  pillButtonSecondary: {
    backgroundColor: profileColors.surfaceMuted,
  },
  pillButtonGhost: {
    backgroundColor: "transparent",
  },
  pillButtonDisabled: {
    opacity: 0.65,
  },
  pillButtonPressed: {
    opacity: 0.82,
  },
  pillButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  pillButtonTextDark: {
    color: profileColors.inkStrong,
  },
  section: {
    marginHorizontal: sizes.md,
    borderRadius: 8,
    backgroundColor: colors.white,
    padding: sizes.md,
    gap: sizes.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileColors.surfaceMuted,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: sizes.md,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: profileColors.ink,
  },
  sectionSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: colors.subtext,
  },
  sectionLink: {
    fontSize: 14,
    fontWeight: "800",
    color: profileColors.brand,
  },
  postList: {
    gap: sizes.md,
  },
  inlineLoader: {
    paddingVertical: sizes.lg,
  },
  emptyState: {
    minHeight: 110,
    borderRadius: 8,
    backgroundColor: profileColors.surfaceSubtle,
    alignItems: "center",
    justifyContent: "center",
    padding: sizes.lg,
    gap: sizes.xs,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.text,
  },
  emptyBody: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    textAlign: "center",
  },
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    padding: sizes.xl,
    gap: sizes.sm,
  },
  centerTitle: {
    fontSize: 19,
    fontWeight: "900",
    color: colors.text,
    textAlign: "center",
  },
  centerText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.subtext,
    textAlign: "center",
  },
  retryButton: {
    marginTop: sizes.md,
    minWidth: 140,
  },
  modalRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: profileColors.overlay,
  },
  menuSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: sizes.lg,
    paddingTop: sizes.sm,
    paddingBottom: 34,
  },
  bottomSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: sizes.lg,
    paddingTop: sizes.sm,
    paddingBottom: 34,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 74,
    height: 5,
    borderRadius: 999,
    backgroundColor: profileColors.surfaceOverlay,
    marginBottom: sizes.md,
  },
  menuRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.md,
  },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    color: profileColors.inkStrong,
  },
  imagePreviewRoot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.black,
  },
  imagePreviewClose: {
    position: "absolute",
    top: 48,
    right: 18,
    zIndex: 1,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.overlayLight,
  },
  imagePreview: {
    width: "100%",
    height: "100%",
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.md,
    marginBottom: sizes.lg,
  },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: profileColors.surfaceIcon,
    alignItems: "center",
    justifyContent: "center",
  },
  optionText: {
    fontSize: 16,
    color: profileColors.inkStrong,
    fontWeight: "700",
    flexShrink: 1,
  },
});

export default profileStyles;
