import { StyleSheet } from "react-native";
import colors from "@/constants/colors";
import sizes from "@/constants/sizes";

const profileColors = {
  page: colors.page,
  brand: colors.brand,
  ink: colors.ink,
  inkMuted: colors.inkMuted,
  inkSoft: colors.inkSoft,
  inkStrong: colors.inkStrong,
  borderStrong: colors.borderStrong,
  borderMuted: colors.borderMuted,
  surfaceMuted: colors.surfaceMuted,
  surfaceSoft: colors.surfaceSoft,
  surfaceAccent: colors.surfaceAccent,
  surfaceSubtle: colors.surfaceSubtle,
  surfaceIcon: colors.surfaceIcon,
  surfaceOverlay: colors.surfaceOverlay,
  overlay: colors.overlay,
  overlayLight: colors.overlayLight,
};

const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: profileColors.page,
  },
  scrollContent: {
    paddingBottom: sizes.xl,
    gap: 8,
  },
  coverImage: {
    width: "100%",
    height: "100%",
  },
  avatarImage: {
    backgroundColor: profileColors.surfaceMuted,
  },
  avatarFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.surfaceAccent,
  },
  avatarFallbackText: {
    color: colors.primary,
    fontWeight: "900",
  },
  fbHero: {
    backgroundColor: colors.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: profileColors.borderStrong,
  },
  fbCover: {
    height: 178,
    marginHorizontal: sizes.md,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    overflow: "hidden",
    backgroundColor: profileColors.borderMuted,
  },
  fbCoverFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.borderMuted,
  },
  fbCoverCamera: {
    position: "absolute",
    right: 12,
    bottom: 12,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  fbHeroInfo: {
    paddingHorizontal: sizes.md,
    paddingBottom: sizes.md,
  },
  fbAvatarRow: {
    height: 70,
    alignItems: "center",
  },
  fbAvatarBorder: {
    borderWidth: 4,
    borderColor: colors.white,
    backgroundColor: colors.white,
    marginTop: -66,
  },
  fbAvatarCamera: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.white,
  },
  fbName: {
    marginTop: 2,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
    color: profileColors.ink,
    textAlign: "center",
  },
  fbUsername: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    color: profileColors.ink,
  },
  fbBio: {
    marginTop: sizes.xs,
    fontSize: 15,
    lineHeight: 20,
    color: profileColors.ink,
    textAlign: "center",
  },
  fbActionRow: {
    marginTop: sizes.md,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  fbOwnActionRow: {
    justifyContent: "flex-end",
  },
  fbProfileDetails: {
    marginTop: sizes.sm,
    paddingTop: sizes.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: profileColors.borderMuted,
    gap: 8,
  },
  fbProfileDetailRow: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  fbProfileDetailText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: profileColors.inkSoft,
  },
  fbProfileDetailStrong: {
    fontWeight: "900",
    color: profileColors.ink,
  },
  fbButton: {
    minHeight: 38,
    paddingHorizontal: 0,
    backgroundColor: profileColors.surfaceMuted,
  },
  fbButtonCompact: {
    minHeight: 32,
    paddingHorizontal: 0,
  },
  fbButtonSecondary: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: profileColors.borderMuted,
  },
  fbIconButton: {
    backgroundColor: "transparent",
    minHeight: "auto",
    height: 32,
    width: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  fbButtonIconSlot: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  fbIconButtonSlot: {
    width: 24,
    height: 24,
  },
  fbButtonText: {
    color: colors.white,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
    flexShrink: 1,
  },
  fbButtonTextDark: {
    color: profileColors.ink,
  },
  fbBody: {
    gap: 8,
  },
  fbCard: {
    marginHorizontal: sizes.md,
    borderRadius: 8,
    backgroundColor: colors.white,
    padding: sizes.md,
    gap: sizes.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: profileColors.surfaceMuted,
  },
  fbCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: sizes.md,
  },
  fbCardTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: profileColors.ink,
  },
  fbComposerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.sm,
  },
  fbComposerInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: sizes.md,
    alignItems: "flex-start",
    justifyContent: "center",
    backgroundColor: profileColors.page,
  },
  fbComposerText: {
    fontSize: 15,
    color: profileColors.inkMuted,
  },
  pillButtonDisabled: {
    opacity: 0.65,
  },
  pillButtonPressed: {
    opacity: 0.82,
  },
  postList: {
    gap: sizes.md,
  },
  inlineLoader: {
    paddingVertical: sizes.lg,
  },
  emptyState: {
    minHeight: 110,
    borderRadius: 8,
    backgroundColor: profileColors.surfaceSubtle,
    alignItems: "center",
    justifyContent: "center",
    padding: sizes.lg,
    gap: sizes.xs,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.text,
  },
  emptyBody: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.subtext,
    textAlign: "center",
  },
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.white,
    padding: sizes.xl,
    gap: sizes.sm,
  },
  centerTitle: {
    fontSize: 19,
    fontWeight: "900",
    color: colors.text,
    textAlign: "center",
  },
  centerText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.subtext,
    textAlign: "center",
  },
  retryButton: {
    marginTop: sizes.md,
    minWidth: 140,
  },
  modalRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: profileColors.overlay,
  },
  menuSheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: sizes.lg,
    paddingTop: sizes.sm,
    paddingBottom: 34,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 74,
    height: 5,
    borderRadius: 999,
    backgroundColor: profileColors.surfaceOverlay,
    marginBottom: sizes.md,
  },
  menuRow: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: sizes.md,
  },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: profileColors.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    color: profileColors.inkStrong,
  },
  imagePreviewRoot: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.black,
  },
  imagePreviewClose: {
    position: "absolute",
    top: 48,
    right: 18,
    zIndex: 1,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: profileColors.overlayLight,
  },
  imagePreview: {
    width: "100%",
    height: "100%",
  },
});

export default profileStyles;
