import colors from "@/constants/colors";
import { StyleSheet } from "react-native";

const createStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
  },
  submitButton: {
    padding: 4,
  },
  submitText: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.primary,
  },
  submitTextDisabled: {
    color: colors.placeholder,
  },
  createBody: {
    flex: 1,
    position: "relative",
  },
  createContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    gap: 12,
  },
  userInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 0,
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surface,
  },
  userName: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.text,
  },
  privacyBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: "transparent",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
    marginTop: 4,
    alignSelf: "flex-start",
  },
  privacyText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.subtext,
  },
  modeHint: {
    fontSize: 13,
    color: colors.subtext,
    lineHeight: 18,
  },
  createTextArea: {
    minHeight: 26,
    fontSize: 18,
    color: colors.text,
    paddingHorizontal: 0,
    paddingVertical: 0,
    lineHeight: 26,
  },
  videoGrid: {
    flexDirection: "row",
    gap: 0,
    marginHorizontal: -16,
  },
  videoCard: {
    flex: 1,
    borderRadius: 0,
    overflow: "hidden",
    backgroundColor: colors.black,
    borderWidth: 0,
  },
  videoRemoveButton: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 3,
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.overlayLight,
  },
  videoPreviewFrame: {
    position: "relative",
    width: "100%",
    aspectRatio: 1,
    backgroundColor: colors.black,
  },
  videoPreview: {
    width: "100%",
    height: "100%",
  },
  videoPreviewFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.overlayBlack65,
    gap: 8,
  },
  videoPreviewFallbackText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "600",
  },
  videoPlayBadge: {
    position: "absolute",
    alignSelf: "center",
    bottom: 10,
    backgroundColor: colors.overlayBlack65,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  videoPlayText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
  },
  videoLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.overlayBlack40,
  },
  bottomToolbar: {
    position: "absolute",
    left: 0,
    right: 0,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: colors.white,
  },
  libraryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
  },
  libraryText: {
    fontSize: 14,
    color: colors.subtext,
    fontWeight: "600",
  },
  fullscreenBackdrop: {
    flex: 1,
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
  },
  closeButton: {
    position: "absolute",
    top: 42,
    right: 16,
    zIndex: 2,
    padding: 6,
  },
  fullscreenVideo: {
    width: "100%",
    height: "100%",
  },
});

export default createStyles;
