import { StyleSheet } from 'react-native';
import COLORS from '../../constants/colors';

const styles = StyleSheet.create({
  welcomeTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  welcomeBackButton: {
    width: 28,
    height: 28,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  welcomeBackText: {
    fontSize: 22,
    lineHeight: 22,
    color: COLORS.text,
    fontWeight: '600',
  },
  welcomeTopTitle: {
    marginLeft: 10,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '800',
    color: COLORS.text,
  },
  welcomeDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginTop: 10,
  },
  welcomeBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingBottom: 26,
  },
  welcomeImage: {
    width: 220,
    height: 220,
    alignSelf: 'center',
    marginBottom: 24,
  },
  welcomeTitle: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 12,
    textAlign: 'center',
  },
  welcomeDesc: {
    fontSize: 19,
    lineHeight: 28,
    color: COLORS.subtext,
    textAlign: 'center',
    maxWidth: 320,
  },
  welcomeButtonWrap: {
    marginTop: 26,
    width: '100%',
    maxWidth: 360,
  },
  welcomeBottomHint: {
    alignItems: 'center',
    paddingBottom: 6,
  },

  // Birthday screen
  birthdayBody: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 16,
  },
  birthdayTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 18,
  },
  pickerWrapper: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 24,
  },
  pickerRow: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 360,
    justifyContent: 'space-between',
  },
  pickerColumn: {
    flex: 1,
    height: 180,
    marginHorizontal: 6,
  },
  pickerItem: {
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerItemText: {
    fontSize: 16,
    color: COLORS.subtext,
  },
  pickerItemTextActive: {
    color: COLORS.text,
    fontWeight: '700',
  },
  pickerIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 72,
    height: 36,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },

  // Terms screen
  termsBody: {
    flex: 1,
    paddingTop: 12,
  },
  termsWeb: {
    height: 420,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
  },
  termsFooter: {
    marginTop: 16,
    alignItems: 'center',
  },
  termsLink: {
    color: COLORS.primary,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
  },

  // Success screen
  successScreen: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 8,
  },
  successContent: {
    flex: 1,
    alignItems: 'center',
  },
  successHeader: {
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 18,
  },
  successTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
    color: COLORS.text,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  successSubtitle: {
    fontSize: 13,
    lineHeight: 19,
    color: COLORS.subtext,
    textAlign: 'center',
    marginTop: 8,
    maxWidth: 300,
  },
  successImageWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    width: '100%',
    paddingVertical: 16,
  },
  successPhone: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 370,
  },
  successPhoneOuter: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 28,
    backgroundColor: '#0B0B0B',
    padding: 10,
  },
  successPhoneScreen: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  successPhoneSpeaker: {
    width: 50,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#1F1F1F',
    marginTop: 12,
  },
  successPhoneCamera: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#1F1F1F',
    marginTop: 8,
  },
  successFacebookBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1877F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 56,
  },
  successFacebookText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    marginTop: -1,
  },
  successAvatarRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 116,
    flexDirection: 'row',
    alignItems: 'center',
  },
  successAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    marginRight: 7,
    backgroundColor: '#E5E7EB',
    overflow: 'hidden',
  },
  successAvatarImage: {
    width: '100%',
    height: '100%',
  },
  successName: {
    fontSize: 12,
    color: COLORS.text,
    fontWeight: '500',
  },
  successFooter: {
    width: '100%',
    paddingBottom: 2,
  },
  successDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  successActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  successActionMuted: {
    flex: 1,
    textAlign: 'center',
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '400',
  },
  successActionSeparator: {
    width: 1,
    height: 18,
    backgroundColor: '#E5E7EB',
  },
  successActionPrimary: {
    flex: 1,
    textAlign: 'center',
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '500',
  },

  // Form styles
  formBody: {
    flex: 1,
    marginTop: 24,
  },
  formLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    marginBottom: 16,
    backgroundColor: COLORS.background,
  },
  input: {
    flex: 1,
    height: '100%',
    fontSize: 16,
    color: COLORS.text,
    paddingVertical: 0,
  },
  eyeIcon: {
    padding: 8,
    marginRight: -8,
  },
  roleContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  roleButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.background,
  },
  roleButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary,
  },
  roleButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.subtext,
  },
  roleButtonTextActive: {
    color: '#FFFFFF',
  },

  ctaButton: {
    width: '100%',
    height: 56,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    marginTop: 24,
  },
  ctaText: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  errorText: {
    marginTop: 6,
    marginBottom: 10,
    fontSize: 13,
    color: COLORS.error,
  },
});

export default styles;
